version: '3.8'

services:
  api-dev:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    expose:
      - "3000"
    volumes:
      - ./api:/app

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-dev 