# Configuration Options:
# Scale containers: docker-compose up --scale api=N (where N is desired instance count)
# Port mapping: Default 80:80 (nginx) - modify for different host port
# Volume mounts: ./api:/app enables hot reloading for development
# Container networking: Services communicate via internal Docker network

version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "3000"
    volumes:
      - ./api:/app

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api 