FROM --platform=linux/amd64 python:3.9

WORKDIR /app

COPY api/requirements.txt .

RUN pip install -r requirements.txt

COPY api/app.py .

EXPOSE 3000

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "3000", "--workers", "4"]